sudo: required
services:
  - docker

before_install:
  - docker build -t mars2025/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mars2025/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-691365429680'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
